site_name: Core Ontology for Biology and Biomedicine
theme: readthedocs
nav:
  - Getting started: index.md
  - Tour:
      - Exploring COB: exploring.md
      - Placing OBO ontologies under COB: obo-bridge.md
      - Integration Tests: integration-tests.md
      - Editors Readme: editors.md
  - How-to guides:
      - Standard ODK workflows:
          - Overview: odk-workflows/index.md
          - Editors Workflow: odk-workflows/EditorsWorkflow.md
          - Release Workflow: odk-workflows/ReleaseWorkflow.md
          - Manage your ODK Repository: odk-workflows/RepoManagement.md
          - Setting up Docker for ODK: odk-workflows/SettingUpDockerForODK.md
          - Imports management: odk-workflows/UpdateImports.md
          - Managing the documentation: odk-workflows/ManageDocumentation.md
          - Continuous Integration: odk-workflows/ContinuousIntegration.md
          - Your ODK Repository Overview: odk-workflows/RepositoryFileStructure.md 
      - Contributing: contributing.md
  - Other:
      - Cite: cite.md
      - History: history.md

