name: Build release files
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'src/ontology/imports/**_import.owl'
      - 'src/ontology/components/**.owl'
      - 'src/ontology/**-edit.owl'

jobs:
  build:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.5.2
    strategy:
      max-parallel: 1
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: work around permission issue
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        
      - name: Update release files
        run: cd src/ontology/ && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx6G' GITHUB_ACTION=true IMP=false PAT=false MIR=false prepare_release
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update release files
          title: 'Update release files'
          body: |
            Updates all release files.
          assignees: sebastianduesing
